# Generated by Django 5.1.5 on 2025-02-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_recipe',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
