# Generated by Django 5.1.5 on 2025-02-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_comments_recipe_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments_recipe',
            options={'ordering': ['-created_at']},
        ),
    ]
