# Generated by Django 5.0 on 2025-02-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_comments_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media/', verbose_name='Image'),
        ),
    ]
